export const destinations = [
  {
    id: 'aswan',
    name: 'Aswan',
    description: 'Experience the beauty of the Nile with golden sunsets and ancient temples.',
    image: '/istockphoto-466090186-612x612.jpg',
    startingPrice: 599,
    packages: [
      {
        id: 'aswan-1',
        name: 'Aswan & Nubian Adventure',
        description: 'Explore the temples of Abu Simbel and the Nubian villages.',
        duration: '3 days',
        groupSize: '2-8 people',
        price: 899,
        includes: ['Accommodation', 'Guided tours', 'Meals', 'Nile cruise'],
        image: '/istockphoto-466090186-612x612.jpg',
      },
      {
        id: 'aswan-2',
        name: 'Luxury Nile Cruise',
        description: 'Relax on a 5-star cruise with gourmet dining and premium service.',
        duration: '5 days',
        groupSize: '2-30 people',
        price: 1899,
        includes: ['Luxury accommodation', 'All meals', 'Premium guide', 'Spa access'],
        image: '/istockphoto-466090186-612x612.jpg',
      },
      {
        id: 'aswan-3',
        name: 'Budget Explorer',
        description: 'Discover Aswan on a budget with essential sightseeing and local experiences.',
        duration: '2 days',
        groupSize: '4-12 people',
        price: 599,
        includes: ['Budget accommodation', 'Basic meals', 'Group tours', 'Local transport'],
        image: '/istockphoto-466090186-612x612.jpg',
      },
    ],
  },
  {
    id: 'cairo',
    name: 'Cairo',
    description: 'The vibrant capital of Egypt where ancient history meets modern city life.',
    image: '/istockphoto-466090186-612x612.jpg',
    startingPrice: 499,
    packages: [
      {
        id: 'cairo-1',
        name: 'Pyramids & Museum Experience',
        description: 'Visit the Great Pyramids and explore the Egyptian Museum with expert guides.',
        duration: '2 days',
        groupSize: '2-10 people',
        price: 649,
        includes: ['Hotel accommodation', 'Guided tours', 'Transport', 'Meals'],
        image: '/istockphoto-466090186-612x612.jpg',
      },
      {
        id: 'cairo-2',
        name: 'Islamic Cairo Tour',
        description: 'Discover the medieval markets, mosques, and cultural heritage of Islamic Cairo.',
        duration: '1 day',
        groupSize: '2-8 people',
        price: 499,
        includes: ['Guide service', 'Transport', 'Lunch', 'Market access'],
        image: '/istockphoto-466090186-612x612.jpg',
      },
      {
        id: 'cairo-3',
        name: 'Ultimate Cairo',
        description: 'Comprehensive tour covering pyramids, museum, and cultural sites.',
        duration: '4 days',
        groupSize: '2-12 people',
        price: 1299,
        includes: ['4-star hotel', 'All guided tours', 'All meals', 'Premium transport'],
        image: '/istockphoto-466090186-612x612.jpg',
      },
    ],
  },
  {
    id: 'luxor',
    name: 'Luxor',
    description: 'Ancient Thebes awaits with the grandest temples and Valley of the Kings.',
    image: '/luxor-valley-of-the-kings-egypt.jpg',
    startingPrice: 699,
    packages: [
      {
        id: 'luxor-1',
        name: 'Valley of the Kings Express',
        description: 'Guided tour of the Valley of the Kings and Karnak Temple in 2 days.',
        duration: '2 days',
        groupSize: '2-10 people',
        price: 799,
        includes: ['Accommodation', 'Expert guide', 'Meals', 'All entries'],
        image: '/valley-kings-luxor-temples.jpg',
      },
      {
        id: 'luxor-2',
        name: 'Luxor Full Immersion',
        description: 'Deep dive into Luxor with exclusive site access and archaeological insights.',
        duration: '4 days',
        groupSize: '2-8 people',
        price: 1599,
        includes: ['Premium hotel', 'Private guide', 'All meals', 'Sunset cruise'],
        image: '/luxor-karnak-temple.jpg',
      },
      {
        id: 'luxor-3',
        name: 'Budget Luxor',
        description: "Experience Luxor's main attractions without breaking the bank.",
        duration: '2 days',
        groupSize: '4-10 people',
        price: 699,
        includes: ['Budget hotel', 'Group guide', 'Meals', 'Basic transport'],
        image: '/luxor-egypt-affordable-tour.jpg',
      },
    ],
  },
  {
    id: 'alexandria',
    name: 'Alexandria',
    description: 'The Mediterranean jewel with ancient history, beaches, and coastal charm.',
    image: '/alexandria-egypt-mediterranean-coast.jpg',
    startingPrice: 449,
    packages: [
      {
        id: 'alex-1',
        name: 'Coastal Getaway',
        description: 'Relax on beautiful beaches and explore ancient ruins in Alexandria.',
        duration: '2 days',
        groupSize: '2-8 people',
        price: 549,
        includes: ['Beach resort', 'Guided tours', 'Meals', 'Water activities'],
        image: '/alexandria-beach-resort.jpg',
      },
      {
        id: 'alex-2',
        name: 'Historical Alexandria',
        description: "Dive deep into Alexandria's rich Greco-Roman heritage.",
        duration: '1 day',
        groupSize: '2-10 people',
        price: 449,
        includes: ['Expert guide', 'Transport', 'Museum entries', 'Lunch'],
        image: '/alexandria-citadel-qaitbay-fortress.jpg',
      },
      {
        id: 'alex-3',
        name: 'Luxury Beach Escape',
        description: 'Five-star resort experience with cultural tours and beach relaxation.',
        duration: '3 days',
        groupSize: '2-20 people',
        price: 1199,
        includes: ['Luxury resort', 'All meals', 'Spa', 'Tour & activities'],
        image: '/placeholder.svg?height=400&width=600',
      },
    ],
  },
  {
    id: 'sinai',
    name: 'Mt. Sinai',
    description: 'Sacred mountain with stunning desert landscapes and spiritual significance.',
    image: '/placeholder.svg?height=400&width=600',
    startingPrice: 399,
    packages: [
      {
        id: 'sinai-1',
        name: 'Mt. Sinai Sunrise Trek',
        description: 'Hike to the summit for a breathtaking sunrise experience.',
        duration: '1 day',
        groupSize: '2-12 people',
        price: 399,
        includes: ['Guide', 'Transport', 'Breakfast', 'Water & snacks'],
        image: '/placeholder.svg?height=400&width=600',
      },
      {
        id: 'sinai-2',
        name: 'Desert Adventure',
        description: 'Multi-day desert exploration with camping and cultural experiences.',
        duration: '3 days',
        groupSize: '4-8 people',
        price: 899,
        includes: ['Desert camp', 'Meals', 'Guide', 'Activities'],
        image: '/placeholder.svg?height=400&width=600',
      },
    ],
  },
];

export const allPackages = destinations.flatMap((dest) =>
  dest.packages.map((pkg) => ({ ...pkg, destinationId: dest.id, destinationName: dest.name })),
);
